// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen.ts';
import type { CreateOrderError, CreateOrderResponse, CreateOrFetchResourceError, CreateOrFetchResourceResponse, GetArrayOfCodecsResponse, GetArrayOfScalarsResponse, GetArrayWithLengthResponse, GetBrandedFieldResponse, GetCodecObjectResponse, GetComposedResponse, GetConstrainedCodecResponse, GetDateFieldResponse, GetDefaultFieldResponse, GetDiscriminatedUnionResponse, GetEnumFieldResponse, GetErrorsOnlyError, GetIntersectionFieldResponse, GetItemWithRegisteredParamResponse, GetLiteralFieldResponse, GetMapFieldResponse, GetNestedResponse, GetNullableFieldResponse, GetNumberWithRangeResponse, GetOptionalFieldResponse, GetOptionalNullableFieldResponse, GetPaginatedComposedResponse, GetReadonlyArrayFieldResponse, GetRecordFieldResponse, GetRefinedFieldResponse, GetScalarBigIntResponse, GetScalarBooleanResponse, GetScalarNumberResponse, GetScalarStringResponse, GetSetFieldResponse, GetStringWithFormatResponse, GetStringWithMinMaxResponse, GetTupleFieldResponse, GetUnionFieldResponse, GetUnionOfLiteralsResponse, SubmitForReviewResponse, UpdateOrderResponse } from '../registry-validator.gen.ts';
import { createOrder, createOrFetchResource, getArrayOfCodecs, getArrayOfScalars, getArrayWithLength, getBrandedField, getCodecObject, getComposed, getConstrainedCodec, getDateField, getDefaultField, getDiscriminatedUnion, getEnumField, getErrorsOnly, getIntersectionField, getItemWithRegisteredParam, getLiteralField, getMapField, getNested, getNullableField, getNumberWithRange, getOptionalField, getOptionalNullableField, getPaginatedComposed, getReadonlyArrayField, getRecordField, getRefinedField, getScalarBigInt, getScalarBoolean, getScalarNumber, getScalarString, getSetField, getStringWithFormat, getStringWithMinMax, getTupleField, getUnionField, getUnionOfLiterals, type Options, submitForReview, updateOrder } from '../sdk.gen.ts';
import type { CreateOrderData, CreateOrFetchResourceData, GetArrayOfCodecsData, GetArrayOfScalarsData, GetArrayWithLengthData, GetBrandedFieldData, GetCodecObjectData, GetComposedData, GetConstrainedCodecData, GetDateFieldData, GetDefaultFieldData, GetDiscriminatedUnionData, GetEnumFieldData, GetErrorsOnlyData, GetIntersectionFieldData, GetItemWithRegisteredParamData, GetLiteralFieldData, GetMapFieldData, GetNestedData, GetNullableFieldData, GetNumberWithRangeData, GetOptionalFieldData, GetOptionalNullableFieldData, GetPaginatedComposedData, GetReadonlyArrayFieldData, GetRecordFieldData, GetRefinedFieldData, GetScalarBigIntData, GetScalarBooleanData, GetScalarNumberData, GetScalarStringData, GetSetFieldData, GetStringWithFormatData, GetStringWithMinMaxData, GetTupleFieldData, GetUnionFieldData, GetUnionOfLiteralsData, SubmitForReviewData, UpdateOrderData } from '../types.gen.ts';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getScalarStringQueryKey = (options?: Options<GetScalarStringData>) => createQueryKey('getScalarString', options);

export const getScalarStringOptions = (options?: Options<GetScalarStringData>) => queryOptions<GetScalarStringResponse, DefaultError, GetScalarStringResponse, ReturnType<typeof getScalarStringQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getScalarString({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getScalarStringQueryKey(options)
});

export const getScalarNumberQueryKey = (options?: Options<GetScalarNumberData>) => createQueryKey('getScalarNumber', options);

export const getScalarNumberOptions = (options?: Options<GetScalarNumberData>) => queryOptions<GetScalarNumberResponse, DefaultError, GetScalarNumberResponse, ReturnType<typeof getScalarNumberQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getScalarNumber({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getScalarNumberQueryKey(options)
});

export const getScalarBooleanQueryKey = (options?: Options<GetScalarBooleanData>) => createQueryKey('getScalarBoolean', options);

export const getScalarBooleanOptions = (options?: Options<GetScalarBooleanData>) => queryOptions<GetScalarBooleanResponse, DefaultError, GetScalarBooleanResponse, ReturnType<typeof getScalarBooleanQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getScalarBoolean({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getScalarBooleanQueryKey(options)
});

export const getScalarBigIntQueryKey = (options?: Options<GetScalarBigIntData>) => createQueryKey('getScalarBigInt', options);

export const getScalarBigIntOptions = (options?: Options<GetScalarBigIntData>) => queryOptions<GetScalarBigIntResponse, DefaultError, GetScalarBigIntResponse, ReturnType<typeof getScalarBigIntQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getScalarBigInt({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getScalarBigIntQueryKey(options)
});

export const getOptionalFieldQueryKey = (options?: Options<GetOptionalFieldData>) => createQueryKey('getOptionalField', options);

export const getOptionalFieldOptions = (options?: Options<GetOptionalFieldData>) => queryOptions<GetOptionalFieldResponse, DefaultError, GetOptionalFieldResponse, ReturnType<typeof getOptionalFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getOptionalField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getOptionalFieldQueryKey(options)
});

export const getNullableFieldQueryKey = (options?: Options<GetNullableFieldData>) => createQueryKey('getNullableField', options);

export const getNullableFieldOptions = (options?: Options<GetNullableFieldData>) => queryOptions<GetNullableFieldResponse, DefaultError, GetNullableFieldResponse, ReturnType<typeof getNullableFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getNullableField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getNullableFieldQueryKey(options)
});

export const getOptionalNullableFieldQueryKey = (options?: Options<GetOptionalNullableFieldData>) => createQueryKey('getOptionalNullableField', options);

export const getOptionalNullableFieldOptions = (options?: Options<GetOptionalNullableFieldData>) => queryOptions<GetOptionalNullableFieldResponse, DefaultError, GetOptionalNullableFieldResponse, ReturnType<typeof getOptionalNullableFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getOptionalNullableField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getOptionalNullableFieldQueryKey(options)
});

export const getEnumFieldQueryKey = (options?: Options<GetEnumFieldData>) => createQueryKey('getEnumField', options);

export const getEnumFieldOptions = (options?: Options<GetEnumFieldData>) => queryOptions<GetEnumFieldResponse, DefaultError, GetEnumFieldResponse, ReturnType<typeof getEnumFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEnumField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEnumFieldQueryKey(options)
});

export const getLiteralFieldQueryKey = (options?: Options<GetLiteralFieldData>) => createQueryKey('getLiteralField', options);

export const getLiteralFieldOptions = (options?: Options<GetLiteralFieldData>) => queryOptions<GetLiteralFieldResponse, DefaultError, GetLiteralFieldResponse, ReturnType<typeof getLiteralFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLiteralField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLiteralFieldQueryKey(options)
});

export const getUnionOfLiteralsQueryKey = (options?: Options<GetUnionOfLiteralsData>) => createQueryKey('getUnionOfLiterals', options);

export const getUnionOfLiteralsOptions = (options?: Options<GetUnionOfLiteralsData>) => queryOptions<GetUnionOfLiteralsResponse, DefaultError, GetUnionOfLiteralsResponse, ReturnType<typeof getUnionOfLiteralsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUnionOfLiterals({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUnionOfLiteralsQueryKey(options)
});

export const getArrayOfScalarsQueryKey = (options?: Options<GetArrayOfScalarsData>) => createQueryKey('getArrayOfScalars', options);

export const getArrayOfScalarsOptions = (options?: Options<GetArrayOfScalarsData>) => queryOptions<GetArrayOfScalarsResponse, DefaultError, GetArrayOfScalarsResponse, ReturnType<typeof getArrayOfScalarsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getArrayOfScalars({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getArrayOfScalarsQueryKey(options)
});

export const getArrayOfCodecsQueryKey = (options?: Options<GetArrayOfCodecsData>) => createQueryKey('getArrayOfCodecs', options);

export const getArrayOfCodecsOptions = (options?: Options<GetArrayOfCodecsData>) => queryOptions<GetArrayOfCodecsResponse, DefaultError, GetArrayOfCodecsResponse, ReturnType<typeof getArrayOfCodecsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getArrayOfCodecs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getArrayOfCodecsQueryKey(options)
});

export const getRecordFieldQueryKey = (options?: Options<GetRecordFieldData>) => createQueryKey('getRecordField', options);

export const getRecordFieldOptions = (options?: Options<GetRecordFieldData>) => queryOptions<GetRecordFieldResponse, DefaultError, GetRecordFieldResponse, ReturnType<typeof getRecordFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRecordField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRecordFieldQueryKey(options)
});

export const getNestedQueryKey = (options?: Options<GetNestedData>) => createQueryKey('getNested', options);

export const getNestedOptions = (options?: Options<GetNestedData>) => queryOptions<GetNestedResponse, DefaultError, GetNestedResponse, ReturnType<typeof getNestedQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getNested({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getNestedQueryKey(options)
});

export const getUnionFieldQueryKey = (options?: Options<GetUnionFieldData>) => createQueryKey('getUnionField', options);

export const getUnionFieldOptions = (options?: Options<GetUnionFieldData>) => queryOptions<GetUnionFieldResponse, DefaultError, GetUnionFieldResponse, ReturnType<typeof getUnionFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUnionField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUnionFieldQueryKey(options)
});

export const getCodecObjectQueryKey = (options?: Options<GetCodecObjectData>) => createQueryKey('getCodecObject', options);

export const getCodecObjectOptions = (options?: Options<GetCodecObjectData>) => queryOptions<GetCodecObjectResponse, DefaultError, GetCodecObjectResponse, ReturnType<typeof getCodecObjectQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCodecObject({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCodecObjectQueryKey(options)
});

export const getComposedQueryKey = (options?: Options<GetComposedData>) => createQueryKey('getComposed', options);

export const getComposedOptions = (options?: Options<GetComposedData>) => queryOptions<GetComposedResponse, DefaultError, GetComposedResponse, ReturnType<typeof getComposedQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getComposed({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getComposedQueryKey(options)
});

export const getPaginatedComposedQueryKey = (options?: Options<GetPaginatedComposedData>) => createQueryKey('getPaginatedComposed', options);

export const getPaginatedComposedOptions = (options?: Options<GetPaginatedComposedData>) => queryOptions<GetPaginatedComposedResponse, DefaultError, GetPaginatedComposedResponse, ReturnType<typeof getPaginatedComposedQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPaginatedComposed({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPaginatedComposedQueryKey(options)
});

export const getStringWithMinMaxQueryKey = (options?: Options<GetStringWithMinMaxData>) => createQueryKey('getStringWithMinMax', options);

export const getStringWithMinMaxOptions = (options?: Options<GetStringWithMinMaxData>) => queryOptions<GetStringWithMinMaxResponse, DefaultError, GetStringWithMinMaxResponse, ReturnType<typeof getStringWithMinMaxQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStringWithMinMax({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStringWithMinMaxQueryKey(options)
});

export const getNumberWithRangeQueryKey = (options?: Options<GetNumberWithRangeData>) => createQueryKey('getNumberWithRange', options);

export const getNumberWithRangeOptions = (options?: Options<GetNumberWithRangeData>) => queryOptions<GetNumberWithRangeResponse, DefaultError, GetNumberWithRangeResponse, ReturnType<typeof getNumberWithRangeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getNumberWithRange({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getNumberWithRangeQueryKey(options)
});

export const getArrayWithLengthQueryKey = (options?: Options<GetArrayWithLengthData>) => createQueryKey('getArrayWithLength', options);

export const getArrayWithLengthOptions = (options?: Options<GetArrayWithLengthData>) => queryOptions<GetArrayWithLengthResponse, DefaultError, GetArrayWithLengthResponse, ReturnType<typeof getArrayWithLengthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getArrayWithLength({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getArrayWithLengthQueryKey(options)
});

export const getStringWithFormatQueryKey = (options?: Options<GetStringWithFormatData>) => createQueryKey('getStringWithFormat', options);

export const getStringWithFormatOptions = (options?: Options<GetStringWithFormatData>) => queryOptions<GetStringWithFormatResponse, DefaultError, GetStringWithFormatResponse, ReturnType<typeof getStringWithFormatQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStringWithFormat({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStringWithFormatQueryKey(options)
});

export const getRefinedFieldQueryKey = (options?: Options<GetRefinedFieldData>) => createQueryKey('getRefinedField', options);

export const getRefinedFieldOptions = (options?: Options<GetRefinedFieldData>) => queryOptions<GetRefinedFieldResponse, DefaultError, GetRefinedFieldResponse, ReturnType<typeof getRefinedFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRefinedField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRefinedFieldQueryKey(options)
});

export const getConstrainedCodecQueryKey = (options?: Options<GetConstrainedCodecData>) => createQueryKey('getConstrainedCodec', options);

export const getConstrainedCodecOptions = (options?: Options<GetConstrainedCodecData>) => queryOptions<GetConstrainedCodecResponse, DefaultError, GetConstrainedCodecResponse, ReturnType<typeof getConstrainedCodecQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getConstrainedCodec({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getConstrainedCodecQueryKey(options)
});

export const getTupleFieldQueryKey = (options?: Options<GetTupleFieldData>) => createQueryKey('getTupleField', options);

export const getTupleFieldOptions = (options?: Options<GetTupleFieldData>) => queryOptions<GetTupleFieldResponse, DefaultError, GetTupleFieldResponse, ReturnType<typeof getTupleFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTupleField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTupleFieldQueryKey(options)
});

export const getIntersectionFieldQueryKey = (options?: Options<GetIntersectionFieldData>) => createQueryKey('getIntersectionField', options);

export const getIntersectionFieldOptions = (options?: Options<GetIntersectionFieldData>) => queryOptions<GetIntersectionFieldResponse, DefaultError, GetIntersectionFieldResponse, ReturnType<typeof getIntersectionFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIntersectionField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIntersectionFieldQueryKey(options)
});

export const getDiscriminatedUnionQueryKey = (options?: Options<GetDiscriminatedUnionData>) => createQueryKey('getDiscriminatedUnion', options);

export const getDiscriminatedUnionOptions = (options?: Options<GetDiscriminatedUnionData>) => queryOptions<GetDiscriminatedUnionResponse, DefaultError, GetDiscriminatedUnionResponse, ReturnType<typeof getDiscriminatedUnionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDiscriminatedUnion({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDiscriminatedUnionQueryKey(options)
});

export const getDateFieldQueryKey = (options?: Options<GetDateFieldData>) => createQueryKey('getDateField', options);

export const getDateFieldOptions = (options?: Options<GetDateFieldData>) => queryOptions<GetDateFieldResponse, DefaultError, GetDateFieldResponse, ReturnType<typeof getDateFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDateField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDateFieldQueryKey(options)
});

export const getSetFieldQueryKey = (options?: Options<GetSetFieldData>) => createQueryKey('getSetField', options);

export const getSetFieldOptions = (options?: Options<GetSetFieldData>) => queryOptions<GetSetFieldResponse, DefaultError, GetSetFieldResponse, ReturnType<typeof getSetFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSetField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSetFieldQueryKey(options)
});

export const getMapFieldQueryKey = (options?: Options<GetMapFieldData>) => createQueryKey('getMapField', options);

export const getMapFieldOptions = (options?: Options<GetMapFieldData>) => queryOptions<GetMapFieldResponse, DefaultError, GetMapFieldResponse, ReturnType<typeof getMapFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMapField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMapFieldQueryKey(options)
});

export const getDefaultFieldQueryKey = (options?: Options<GetDefaultFieldData>) => createQueryKey('getDefaultField', options);

export const getDefaultFieldOptions = (options?: Options<GetDefaultFieldData>) => queryOptions<GetDefaultFieldResponse, DefaultError, GetDefaultFieldResponse, ReturnType<typeof getDefaultFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDefaultField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDefaultFieldQueryKey(options)
});

export const getReadonlyArrayFieldQueryKey = (options?: Options<GetReadonlyArrayFieldData>) => createQueryKey('getReadonlyArrayField', options);

export const getReadonlyArrayFieldOptions = (options?: Options<GetReadonlyArrayFieldData>) => queryOptions<GetReadonlyArrayFieldResponse, DefaultError, GetReadonlyArrayFieldResponse, ReturnType<typeof getReadonlyArrayFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getReadonlyArrayField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getReadonlyArrayFieldQueryKey(options)
});

export const getBrandedFieldQueryKey = (options?: Options<GetBrandedFieldData>) => createQueryKey('getBrandedField', options);

export const getBrandedFieldOptions = (options?: Options<GetBrandedFieldData>) => queryOptions<GetBrandedFieldResponse, DefaultError, GetBrandedFieldResponse, ReturnType<typeof getBrandedFieldQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBrandedField({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBrandedFieldQueryKey(options)
});

export const createOrFetchResourceMutation = (options?: Partial<Options<CreateOrFetchResourceData>>): UseMutationOptions<CreateOrFetchResourceResponse, CreateOrFetchResourceError, Options<CreateOrFetchResourceData>> => {
    const mutationOptions: UseMutationOptions<CreateOrFetchResourceResponse, CreateOrFetchResourceError, Options<CreateOrFetchResourceData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createOrFetchResource({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getErrorsOnlyQueryKey = (options?: Options<GetErrorsOnlyData>) => createQueryKey('getErrorsOnly', options);

export const getErrorsOnlyOptions = (options?: Options<GetErrorsOnlyData>) => queryOptions<unknown, GetErrorsOnlyError, unknown, ReturnType<typeof getErrorsOnlyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getErrorsOnly({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getErrorsOnlyQueryKey(options)
});

export const getItemWithRegisteredParamQueryKey = (options: Options<GetItemWithRegisteredParamData>) => createQueryKey('getItemWithRegisteredParam', options);

export const getItemWithRegisteredParamOptions = (options: Options<GetItemWithRegisteredParamData>) => queryOptions<GetItemWithRegisteredParamResponse, DefaultError, GetItemWithRegisteredParamResponse, ReturnType<typeof getItemWithRegisteredParamQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getItemWithRegisteredParam({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getItemWithRegisteredParamQueryKey(options)
});

export const createOrderMutation = (options?: Partial<Options<CreateOrderData>>): UseMutationOptions<CreateOrderResponse, CreateOrderError, Options<CreateOrderData>> => {
    const mutationOptions: UseMutationOptions<CreateOrderResponse, CreateOrderError, Options<CreateOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateOrderMutation = (options?: Partial<Options<UpdateOrderData>>): UseMutationOptions<UpdateOrderResponse, DefaultError, Options<UpdateOrderData>> => {
    const mutationOptions: UseMutationOptions<UpdateOrderResponse, DefaultError, Options<UpdateOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const submitForReviewMutation = (options?: Partial<Options<SubmitForReviewData>>): UseMutationOptions<SubmitForReviewResponse, DefaultError, Options<SubmitForReviewData>> => {
    const mutationOptions: UseMutationOptions<SubmitForReviewResponse, DefaultError, Options<SubmitForReviewData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await submitForReview({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
