// This file is auto-generated by @hey-api/openapi-ts

import { ArrayOfCodecs, ArrayOfScalars, ArrayWithLength, BadRequestError, BrandedField, CodecObject, Composed, ConstrainedCodec, DateField, DefaultField, DiscriminatedUnion, EnumField, IntersectionField, LiteralField, MapField, Nested, NotFoundError, NullableField, NumberWithRange, OptionalField, OptionalNullableField, PaginatedComposed, ReadonlyArrayField, RecordField, RefinedField, ResourceCreated, ResourceFetched, ScalarBigInt, ScalarBoolean, ScalarNumber, ScalarString, ServerError, SetField, StringWithFormat, StringWithMinMax, TupleField, UnionField, UnionOfLiterals } from '#test-fixtures/schemas';
import { z } from 'zod';

export type GetScalarStringResponses = {
    200: z.output<typeof ScalarString>;
};

export type GetScalarStringResponse = GetScalarStringResponses[keyof GetScalarStringResponses];

export const getScalarStringTransformer = async (data: unknown): Promise<z.output<typeof ScalarString>> => await ScalarString.parseAsync(data);

export type GetScalarNumberResponses = {
    200: z.output<typeof ScalarNumber>;
};

export type GetScalarNumberResponse = GetScalarNumberResponses[keyof GetScalarNumberResponses];

export const getScalarNumberTransformer = async (data: unknown): Promise<z.output<typeof ScalarNumber>> => await ScalarNumber.parseAsync(data);

export type GetScalarBooleanResponses = {
    200: z.output<typeof ScalarBoolean>;
};

export type GetScalarBooleanResponse = GetScalarBooleanResponses[keyof GetScalarBooleanResponses];

export const getScalarBooleanTransformer = async (data: unknown): Promise<z.output<typeof ScalarBoolean>> => await ScalarBoolean.parseAsync(data);

export type GetScalarBigIntResponses = {
    200: z.output<typeof ScalarBigInt>;
};

export type GetScalarBigIntResponse = GetScalarBigIntResponses[keyof GetScalarBigIntResponses];

export const getScalarBigIntTransformer = async (data: unknown): Promise<z.output<typeof ScalarBigInt>> => await ScalarBigInt.parseAsync(data);

export type GetOptionalFieldResponses = {
    200: z.output<typeof OptionalField>;
};

export type GetOptionalFieldResponse = GetOptionalFieldResponses[keyof GetOptionalFieldResponses];

export const getOptionalFieldTransformer = async (data: unknown): Promise<z.output<typeof OptionalField>> => await OptionalField.parseAsync(data);

export type GetNullableFieldResponses = {
    200: z.output<typeof NullableField>;
};

export type GetNullableFieldResponse = GetNullableFieldResponses[keyof GetNullableFieldResponses];

export const getNullableFieldTransformer = async (data: unknown): Promise<z.output<typeof NullableField>> => await NullableField.parseAsync(data);

export type GetOptionalNullableFieldResponses = {
    200: z.output<typeof OptionalNullableField>;
};

export type GetOptionalNullableFieldResponse = GetOptionalNullableFieldResponses[keyof GetOptionalNullableFieldResponses];

export const getOptionalNullableFieldTransformer = async (data: unknown): Promise<z.output<typeof OptionalNullableField>> => await OptionalNullableField.parseAsync(data);

export type GetEnumFieldResponses = {
    200: z.output<typeof EnumField>;
};

export type GetEnumFieldResponse = GetEnumFieldResponses[keyof GetEnumFieldResponses];

export const getEnumFieldTransformer = async (data: unknown): Promise<z.output<typeof EnumField>> => await EnumField.parseAsync(data);

export type GetLiteralFieldResponses = {
    200: z.output<typeof LiteralField>;
};

export type GetLiteralFieldResponse = GetLiteralFieldResponses[keyof GetLiteralFieldResponses];

export const getLiteralFieldTransformer = async (data: unknown): Promise<z.output<typeof LiteralField>> => await LiteralField.parseAsync(data);

export type GetUnionOfLiteralsResponses = {
    200: z.output<typeof UnionOfLiterals>;
};

export type GetUnionOfLiteralsResponse = GetUnionOfLiteralsResponses[keyof GetUnionOfLiteralsResponses];

export const getUnionOfLiteralsTransformer = async (data: unknown): Promise<z.output<typeof UnionOfLiterals>> => await UnionOfLiterals.parseAsync(data);

export type GetArrayOfScalarsResponses = {
    200: z.output<typeof ArrayOfScalars>;
};

export type GetArrayOfScalarsResponse = GetArrayOfScalarsResponses[keyof GetArrayOfScalarsResponses];

export const getArrayOfScalarsTransformer = async (data: unknown): Promise<z.output<typeof ArrayOfScalars>> => await ArrayOfScalars.parseAsync(data);

export type GetArrayOfCodecsResponses = {
    200: z.output<typeof ArrayOfCodecs>;
};

export type GetArrayOfCodecsResponse = GetArrayOfCodecsResponses[keyof GetArrayOfCodecsResponses];

export const getArrayOfCodecsTransformer = async (data: unknown): Promise<z.output<typeof ArrayOfCodecs>> => await ArrayOfCodecs.parseAsync(data);

export type GetRecordFieldResponses = {
    200: z.output<typeof RecordField>;
};

export type GetRecordFieldResponse = GetRecordFieldResponses[keyof GetRecordFieldResponses];

export const getRecordFieldTransformer = async (data: unknown): Promise<z.output<typeof RecordField>> => await RecordField.parseAsync(data);

export type GetNestedResponses = {
    200: z.output<typeof Nested>;
};

export type GetNestedResponse = GetNestedResponses[keyof GetNestedResponses];

export const getNestedTransformer = async (data: unknown): Promise<z.output<typeof Nested>> => await Nested.parseAsync(data);

export type GetUnionFieldResponses = {
    200: z.output<typeof UnionField>;
};

export type GetUnionFieldResponse = GetUnionFieldResponses[keyof GetUnionFieldResponses];

export const getUnionFieldTransformer = async (data: unknown): Promise<z.output<typeof UnionField>> => await UnionField.parseAsync(data);

export type GetCodecObjectResponses = {
    200: z.output<typeof CodecObject>;
};

export type GetCodecObjectResponse = GetCodecObjectResponses[keyof GetCodecObjectResponses];

export const getCodecObjectTransformer = async (data: unknown): Promise<z.output<typeof CodecObject>> => await CodecObject.parseAsync(data);

export type GetComposedResponses = {
    200: z.output<typeof Composed>;
};

export type GetComposedResponse = GetComposedResponses[keyof GetComposedResponses];

export const getComposedTransformer = async (data: unknown): Promise<z.output<typeof Composed>> => await Composed.parseAsync(data);

export type GetPaginatedComposedResponses = {
    200: z.output<typeof PaginatedComposed>;
};

export type GetPaginatedComposedResponse = GetPaginatedComposedResponses[keyof GetPaginatedComposedResponses];

export const getPaginatedComposedTransformer = async (data: unknown): Promise<z.output<typeof PaginatedComposed>> => await PaginatedComposed.parseAsync(data);

export type GetStringWithMinMaxResponses = {
    200: z.output<typeof StringWithMinMax>;
};

export type GetStringWithMinMaxResponse = GetStringWithMinMaxResponses[keyof GetStringWithMinMaxResponses];

export const getStringWithMinMaxTransformer = async (data: unknown): Promise<z.output<typeof StringWithMinMax>> => await StringWithMinMax.parseAsync(data);

export type GetNumberWithRangeResponses = {
    200: z.output<typeof NumberWithRange>;
};

export type GetNumberWithRangeResponse = GetNumberWithRangeResponses[keyof GetNumberWithRangeResponses];

export const getNumberWithRangeTransformer = async (data: unknown): Promise<z.output<typeof NumberWithRange>> => await NumberWithRange.parseAsync(data);

export type GetArrayWithLengthResponses = {
    200: z.output<typeof ArrayWithLength>;
};

export type GetArrayWithLengthResponse = GetArrayWithLengthResponses[keyof GetArrayWithLengthResponses];

export const getArrayWithLengthTransformer = async (data: unknown): Promise<z.output<typeof ArrayWithLength>> => await ArrayWithLength.parseAsync(data);

export type GetStringWithFormatResponses = {
    200: z.output<typeof StringWithFormat>;
};

export type GetStringWithFormatResponse = GetStringWithFormatResponses[keyof GetStringWithFormatResponses];

export const getStringWithFormatTransformer = async (data: unknown): Promise<z.output<typeof StringWithFormat>> => await StringWithFormat.parseAsync(data);

export type GetRefinedFieldResponses = {
    200: z.output<typeof RefinedField>;
};

export type GetRefinedFieldResponse = GetRefinedFieldResponses[keyof GetRefinedFieldResponses];

export const getRefinedFieldTransformer = async (data: unknown): Promise<z.output<typeof RefinedField>> => await RefinedField.parseAsync(data);

export type GetConstrainedCodecResponses = {
    200: z.output<typeof ConstrainedCodec>;
};

export type GetConstrainedCodecResponse = GetConstrainedCodecResponses[keyof GetConstrainedCodecResponses];

export const getConstrainedCodecTransformer = async (data: unknown): Promise<z.output<typeof ConstrainedCodec>> => await ConstrainedCodec.parseAsync(data);

export type GetTupleFieldResponses = {
    200: z.output<typeof TupleField>;
};

export type GetTupleFieldResponse = GetTupleFieldResponses[keyof GetTupleFieldResponses];

export const getTupleFieldTransformer = async (data: unknown): Promise<z.output<typeof TupleField>> => await TupleField.parseAsync(data);

export type GetIntersectionFieldResponses = {
    200: z.output<typeof IntersectionField>;
};

export type GetIntersectionFieldResponse = GetIntersectionFieldResponses[keyof GetIntersectionFieldResponses];

export const getIntersectionFieldTransformer = async (data: unknown): Promise<z.output<typeof IntersectionField>> => await IntersectionField.parseAsync(data);

export type GetDiscriminatedUnionResponses = {
    200: z.output<typeof DiscriminatedUnion>;
};

export type GetDiscriminatedUnionResponse = GetDiscriminatedUnionResponses[keyof GetDiscriminatedUnionResponses];

export const getDiscriminatedUnionTransformer = async (data: unknown): Promise<z.output<typeof DiscriminatedUnion>> => await DiscriminatedUnion.parseAsync(data);

export type GetDateFieldResponses = {
    200: z.output<typeof DateField>;
};

export type GetDateFieldResponse = GetDateFieldResponses[keyof GetDateFieldResponses];

export const getDateFieldTransformer = async (data: unknown): Promise<z.output<typeof DateField>> => await DateField.parseAsync(data);

export type GetSetFieldResponses = {
    200: z.output<typeof SetField>;
};

export type GetSetFieldResponse = GetSetFieldResponses[keyof GetSetFieldResponses];

export const getSetFieldTransformer = async (data: unknown): Promise<z.output<typeof SetField>> => await SetField.parseAsync(data);

export type GetMapFieldResponses = {
    200: z.output<typeof MapField>;
};

export type GetMapFieldResponse = GetMapFieldResponses[keyof GetMapFieldResponses];

export const getMapFieldTransformer = async (data: unknown): Promise<z.output<typeof MapField>> => await MapField.parseAsync(data);

export type GetDefaultFieldResponses = {
    200: z.output<typeof DefaultField>;
};

export type GetDefaultFieldResponse = GetDefaultFieldResponses[keyof GetDefaultFieldResponses];

export const getDefaultFieldTransformer = async (data: unknown): Promise<z.output<typeof DefaultField>> => await DefaultField.parseAsync(data);

export type GetReadonlyArrayFieldResponses = {
    200: z.output<typeof ReadonlyArrayField>;
};

export type GetReadonlyArrayFieldResponse = GetReadonlyArrayFieldResponses[keyof GetReadonlyArrayFieldResponses];

export const getReadonlyArrayFieldTransformer = async (data: unknown): Promise<z.output<typeof ReadonlyArrayField>> => await ReadonlyArrayField.parseAsync(data);

export type GetBrandedFieldResponses = {
    200: z.output<typeof BrandedField>;
};

export type GetBrandedFieldResponse = GetBrandedFieldResponses[keyof GetBrandedFieldResponses];

export const getBrandedFieldTransformer = async (data: unknown): Promise<z.output<typeof BrandedField>> => await BrandedField.parseAsync(data);

export type CreateOrFetchResourceResponses = {
    200: z.output<typeof ResourceFetched>;
    201: z.output<typeof ResourceCreated>;
};

export type CreateOrFetchResourceResponse = CreateOrFetchResourceResponses[keyof CreateOrFetchResourceResponses];

export type CreateOrFetchResourceErrors = {
    400: z.output<typeof BadRequestError>;
    404: z.output<typeof NotFoundError>;
    500: z.output<typeof ServerError>;
};

export type CreateOrFetchResourceError = CreateOrFetchResourceErrors[keyof CreateOrFetchResourceErrors];

export const createOrFetchResourceTransformer = async (data: unknown): Promise<z.output<typeof ResourceFetched> | z.output<typeof ResourceCreated>> => await z.union([ResourceFetched, ResourceCreated]).parseAsync(data);

export type GetErrorsOnlyErrors = {
    400: z.output<typeof BadRequestError>;
    500: z.output<typeof ServerError>;
};

export type GetErrorsOnlyError = GetErrorsOnlyErrors[keyof GetErrorsOnlyErrors];

export type GetItemWithRegisteredParamResponses = {
    200: z.output<typeof ScalarString>;
};

export type GetItemWithRegisteredParamResponse = GetItemWithRegisteredParamResponses[keyof GetItemWithRegisteredParamResponses];

export const getItemWithRegisteredParamTransformer = async (data: unknown): Promise<z.output<typeof ScalarString>> => await ScalarString.parseAsync(data);
