// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';
import { ArrayOfCodecs, ArrayOfScalars, ArrayWithLength, BadRequestError, BlockNumberPathParams, BrandedField, CodecObject, Composed, ConstrainedCodec, CreateOrderRequest, DateField, DefaultField, DiscriminatedUnion, EnumField, IntersectionField, LiteralField, MapField, Nested, NotFoundError, NullableField, NumberWithRange, OptionalField, OptionalNullableField, OrderIdPathParams, PaginatedComposed, ReadonlyArrayField, RecentEventsQuery, RecordField, RefinedField, ResourceCreated, ResourceFetched, ScalarBigInt, ScalarBoolean, ScalarNumber, ScalarString, ServerError, SetField, StringWithFormat, StringWithMinMax, SubmitForReviewRequest, TupleField, UnionField, UnionOfLiterals, UpdateOrderRequest } from '#test-fixtures/schemas';
import { z, type ZodError } from 'zod';

import { client } from './client.gen.ts';
import { createOrder as createOrder2, createOrFetchResource as createOrFetchResource2, getArrayOfCodecs as getArrayOfCodecs2, getArrayOfScalars as getArrayOfScalars2, getArrayWithLength as getArrayWithLength2, getBrandedField as getBrandedField2, getCodecObject as getCodecObject2, getComposed as getComposed2, getConstrainedCodec as getConstrainedCodec2, getDateField as getDateField2, getDefaultField as getDefaultField2, getDiscriminatedUnion as getDiscriminatedUnion2, getEnumField as getEnumField2, getErrorsOnly as getErrorsOnly2, getIntersectionField as getIntersectionField2, getItemWithRegisteredParam as getItemWithRegisteredParam2, getLiteralField as getLiteralField2, getMapField as getMapField2, getNested as getNested2, getNullableField as getNullableField2, getNumberWithRange as getNumberWithRange2, getOptionalField as getOptionalField2, getOptionalNullableField as getOptionalNullableField2, getPaginatedComposed as getPaginatedComposed2, getReadonlyArrayField as getReadonlyArrayField2, getRecordField as getRecordField2, getRefinedField as getRefinedField2, getScalarBigInt as getScalarBigInt2, getScalarBoolean as getScalarBoolean2, getScalarNumber as getScalarNumber2, getScalarString as getScalarString2, getSetField as getSetField2, getStringWithFormat as getStringWithFormat2, getStringWithMinMax as getStringWithMinMax2, getTupleField as getTupleField2, getUnionField as getUnionField2, getUnionOfLiterals as getUnionOfLiterals2, listRecentEvents as listRecentEvents2, lookupBlock as lookupBlock2, type Options, submitForReview as submitForReview2, updateOrder as updateOrder2 } from './sdk.gen.ts';
import type { CreateOrderData, CreateOrFetchResourceData, GetArrayOfCodecsData, GetArrayOfScalarsData, GetArrayWithLengthData, GetBrandedFieldData, GetCodecObjectData, GetComposedData, GetConstrainedCodecData, GetDateFieldData, GetDefaultFieldData, GetDiscriminatedUnionData, GetEnumFieldData, GetErrorsOnlyData, GetIntersectionFieldData, GetItemWithRegisteredParamData, GetLiteralFieldData, GetMapFieldData, GetNestedData, GetNullableFieldData, GetNumberWithRangeData, GetOptionalFieldData, GetOptionalNullableFieldData, GetPaginatedComposedData, GetReadonlyArrayFieldData, GetRecordFieldData, GetRefinedFieldData, GetScalarBigIntData, GetScalarBooleanData, GetScalarNumberData, GetScalarStringData, GetSetFieldData, GetStringWithFormatData, GetStringWithMinMaxData, GetTupleFieldData, GetUnionFieldData, GetUnionOfLiteralsData, ListRecentEventsData, LookupBlockData, SubmitForReviewData, UpdateOrderData } from './types.gen.ts';

export type GetScalarStringResponses = {
    200: z.output<typeof ScalarString>;
};

export type GetScalarStringResponse = GetScalarStringResponses[keyof GetScalarStringResponses];

export const getScalarStringTransformer = async (data: unknown): Promise<z.output<typeof ScalarString>> => await ScalarString.parseAsync(data);

export const getScalarString = async <ThrowOnError extends boolean = false>(options?: Options<GetScalarStringData, ThrowOnError>) => await getScalarString2(options);

export type GetScalarNumberResponses = {
    200: z.output<typeof ScalarNumber>;
};

export type GetScalarNumberResponse = GetScalarNumberResponses[keyof GetScalarNumberResponses];

export const getScalarNumberTransformer = async (data: unknown): Promise<z.output<typeof ScalarNumber>> => await ScalarNumber.parseAsync(data);

export const getScalarNumber = async <ThrowOnError extends boolean = false>(options?: Options<GetScalarNumberData, ThrowOnError>) => await getScalarNumber2(options);

export type GetScalarBooleanResponses = {
    200: z.output<typeof ScalarBoolean>;
};

export type GetScalarBooleanResponse = GetScalarBooleanResponses[keyof GetScalarBooleanResponses];

export const getScalarBooleanTransformer = async (data: unknown): Promise<z.output<typeof ScalarBoolean>> => await ScalarBoolean.parseAsync(data);

export const getScalarBoolean = async <ThrowOnError extends boolean = false>(options?: Options<GetScalarBooleanData, ThrowOnError>) => await getScalarBoolean2(options);

export type GetScalarBigIntResponses = {
    200: z.output<typeof ScalarBigInt>;
};

export type GetScalarBigIntResponse = GetScalarBigIntResponses[keyof GetScalarBigIntResponses];

export const getScalarBigIntTransformer = async (data: unknown): Promise<z.output<typeof ScalarBigInt>> => await ScalarBigInt.parseAsync(data);

export const getScalarBigInt = async <ThrowOnError extends boolean = false>(options?: Options<GetScalarBigIntData, ThrowOnError>) => await getScalarBigInt2(options);

export type GetOptionalFieldResponses = {
    200: z.output<typeof OptionalField>;
};

export type GetOptionalFieldResponse = GetOptionalFieldResponses[keyof GetOptionalFieldResponses];

export const getOptionalFieldTransformer = async (data: unknown): Promise<z.output<typeof OptionalField>> => await OptionalField.parseAsync(data);

export const getOptionalField = async <ThrowOnError extends boolean = false>(options?: Options<GetOptionalFieldData, ThrowOnError>) => await getOptionalField2(options);

export type GetNullableFieldResponses = {
    200: z.output<typeof NullableField>;
};

export type GetNullableFieldResponse = GetNullableFieldResponses[keyof GetNullableFieldResponses];

export const getNullableFieldTransformer = async (data: unknown): Promise<z.output<typeof NullableField>> => await NullableField.parseAsync(data);

export const getNullableField = async <ThrowOnError extends boolean = false>(options?: Options<GetNullableFieldData, ThrowOnError>) => await getNullableField2(options);

export type GetOptionalNullableFieldResponses = {
    200: z.output<typeof OptionalNullableField>;
};

export type GetOptionalNullableFieldResponse = GetOptionalNullableFieldResponses[keyof GetOptionalNullableFieldResponses];

export const getOptionalNullableFieldTransformer = async (data: unknown): Promise<z.output<typeof OptionalNullableField>> => await OptionalNullableField.parseAsync(data);

export const getOptionalNullableField = async <ThrowOnError extends boolean = false>(options?: Options<GetOptionalNullableFieldData, ThrowOnError>) => await getOptionalNullableField2(options);

export type GetEnumFieldResponses = {
    200: z.output<typeof EnumField>;
};

export type GetEnumFieldResponse = GetEnumFieldResponses[keyof GetEnumFieldResponses];

export const getEnumFieldTransformer = async (data: unknown): Promise<z.output<typeof EnumField>> => await EnumField.parseAsync(data);

export const getEnumField = async <ThrowOnError extends boolean = false>(options?: Options<GetEnumFieldData, ThrowOnError>) => await getEnumField2(options);

export type GetLiteralFieldResponses = {
    200: z.output<typeof LiteralField>;
};

export type GetLiteralFieldResponse = GetLiteralFieldResponses[keyof GetLiteralFieldResponses];

export const getLiteralFieldTransformer = async (data: unknown): Promise<z.output<typeof LiteralField>> => await LiteralField.parseAsync(data);

export const getLiteralField = async <ThrowOnError extends boolean = false>(options?: Options<GetLiteralFieldData, ThrowOnError>) => await getLiteralField2(options);

export type GetUnionOfLiteralsResponses = {
    200: z.output<typeof UnionOfLiterals>;
};

export type GetUnionOfLiteralsResponse = GetUnionOfLiteralsResponses[keyof GetUnionOfLiteralsResponses];

export const getUnionOfLiteralsTransformer = async (data: unknown): Promise<z.output<typeof UnionOfLiterals>> => await UnionOfLiterals.parseAsync(data);

export const getUnionOfLiterals = async <ThrowOnError extends boolean = false>(options?: Options<GetUnionOfLiteralsData, ThrowOnError>) => await getUnionOfLiterals2(options);

export type GetArrayOfScalarsResponses = {
    200: z.output<typeof ArrayOfScalars>;
};

export type GetArrayOfScalarsResponse = GetArrayOfScalarsResponses[keyof GetArrayOfScalarsResponses];

export const getArrayOfScalarsTransformer = async (data: unknown): Promise<z.output<typeof ArrayOfScalars>> => await ArrayOfScalars.parseAsync(data);

export const getArrayOfScalars = async <ThrowOnError extends boolean = false>(options?: Options<GetArrayOfScalarsData, ThrowOnError>) => await getArrayOfScalars2(options);

export type GetArrayOfCodecsResponses = {
    200: z.output<typeof ArrayOfCodecs>;
};

export type GetArrayOfCodecsResponse = GetArrayOfCodecsResponses[keyof GetArrayOfCodecsResponses];

export const getArrayOfCodecsTransformer = async (data: unknown): Promise<z.output<typeof ArrayOfCodecs>> => await ArrayOfCodecs.parseAsync(data);

export const getArrayOfCodecs = async <ThrowOnError extends boolean = false>(options?: Options<GetArrayOfCodecsData, ThrowOnError>) => await getArrayOfCodecs2(options);

export type GetRecordFieldResponses = {
    200: z.output<typeof RecordField>;
};

export type GetRecordFieldResponse = GetRecordFieldResponses[keyof GetRecordFieldResponses];

export const getRecordFieldTransformer = async (data: unknown): Promise<z.output<typeof RecordField>> => await RecordField.parseAsync(data);

export const getRecordField = async <ThrowOnError extends boolean = false>(options?: Options<GetRecordFieldData, ThrowOnError>) => await getRecordField2(options);

export type GetNestedResponses = {
    200: z.output<typeof Nested>;
};

export type GetNestedResponse = GetNestedResponses[keyof GetNestedResponses];

export const getNestedTransformer = async (data: unknown): Promise<z.output<typeof Nested>> => await Nested.parseAsync(data);

export const getNested = async <ThrowOnError extends boolean = false>(options?: Options<GetNestedData, ThrowOnError>) => await getNested2(options);

export type GetUnionFieldResponses = {
    200: z.output<typeof UnionField>;
};

export type GetUnionFieldResponse = GetUnionFieldResponses[keyof GetUnionFieldResponses];

export const getUnionFieldTransformer = async (data: unknown): Promise<z.output<typeof UnionField>> => await UnionField.parseAsync(data);

export const getUnionField = async <ThrowOnError extends boolean = false>(options?: Options<GetUnionFieldData, ThrowOnError>) => await getUnionField2(options);

export type GetCodecObjectResponses = {
    200: z.output<typeof CodecObject>;
};

export type GetCodecObjectResponse = GetCodecObjectResponses[keyof GetCodecObjectResponses];

export const getCodecObjectTransformer = async (data: unknown): Promise<z.output<typeof CodecObject>> => await CodecObject.parseAsync(data);

export const getCodecObject = async <ThrowOnError extends boolean = false>(options?: Options<GetCodecObjectData, ThrowOnError>) => await getCodecObject2(options);

export type GetComposedResponses = {
    200: z.output<typeof Composed>;
};

export type GetComposedResponse = GetComposedResponses[keyof GetComposedResponses];

export const getComposedTransformer = async (data: unknown): Promise<z.output<typeof Composed>> => await Composed.parseAsync(data);

export const getComposed = async <ThrowOnError extends boolean = false>(options?: Options<GetComposedData, ThrowOnError>) => await getComposed2(options);

export type GetPaginatedComposedResponses = {
    200: z.output<typeof PaginatedComposed>;
};

export type GetPaginatedComposedResponse = GetPaginatedComposedResponses[keyof GetPaginatedComposedResponses];

export const getPaginatedComposedTransformer = async (data: unknown): Promise<z.output<typeof PaginatedComposed>> => await PaginatedComposed.parseAsync(data);

export const getPaginatedComposed = async <ThrowOnError extends boolean = false>(options?: Options<GetPaginatedComposedData, ThrowOnError>) => await getPaginatedComposed2(options);

export type GetStringWithMinMaxResponses = {
    200: z.output<typeof StringWithMinMax>;
};

export type GetStringWithMinMaxResponse = GetStringWithMinMaxResponses[keyof GetStringWithMinMaxResponses];

export const getStringWithMinMaxTransformer = async (data: unknown): Promise<z.output<typeof StringWithMinMax>> => await StringWithMinMax.parseAsync(data);

export const getStringWithMinMax = async <ThrowOnError extends boolean = false>(options?: Options<GetStringWithMinMaxData, ThrowOnError>) => await getStringWithMinMax2(options);

export type GetNumberWithRangeResponses = {
    200: z.output<typeof NumberWithRange>;
};

export type GetNumberWithRangeResponse = GetNumberWithRangeResponses[keyof GetNumberWithRangeResponses];

export const getNumberWithRangeTransformer = async (data: unknown): Promise<z.output<typeof NumberWithRange>> => await NumberWithRange.parseAsync(data);

export const getNumberWithRange = async <ThrowOnError extends boolean = false>(options?: Options<GetNumberWithRangeData, ThrowOnError>) => await getNumberWithRange2(options);

export type GetArrayWithLengthResponses = {
    200: z.output<typeof ArrayWithLength>;
};

export type GetArrayWithLengthResponse = GetArrayWithLengthResponses[keyof GetArrayWithLengthResponses];

export const getArrayWithLengthTransformer = async (data: unknown): Promise<z.output<typeof ArrayWithLength>> => await ArrayWithLength.parseAsync(data);

export const getArrayWithLength = async <ThrowOnError extends boolean = false>(options?: Options<GetArrayWithLengthData, ThrowOnError>) => await getArrayWithLength2(options);

export type GetStringWithFormatResponses = {
    200: z.output<typeof StringWithFormat>;
};

export type GetStringWithFormatResponse = GetStringWithFormatResponses[keyof GetStringWithFormatResponses];

export const getStringWithFormatTransformer = async (data: unknown): Promise<z.output<typeof StringWithFormat>> => await StringWithFormat.parseAsync(data);

export const getStringWithFormat = async <ThrowOnError extends boolean = false>(options?: Options<GetStringWithFormatData, ThrowOnError>) => await getStringWithFormat2(options);

export type GetRefinedFieldResponses = {
    200: z.output<typeof RefinedField>;
};

export type GetRefinedFieldResponse = GetRefinedFieldResponses[keyof GetRefinedFieldResponses];

export const getRefinedFieldTransformer = async (data: unknown): Promise<z.output<typeof RefinedField>> => await RefinedField.parseAsync(data);

export const getRefinedField = async <ThrowOnError extends boolean = false>(options?: Options<GetRefinedFieldData, ThrowOnError>) => await getRefinedField2(options);

export type GetConstrainedCodecResponses = {
    200: z.output<typeof ConstrainedCodec>;
};

export type GetConstrainedCodecResponse = GetConstrainedCodecResponses[keyof GetConstrainedCodecResponses];

export const getConstrainedCodecTransformer = async (data: unknown): Promise<z.output<typeof ConstrainedCodec>> => await ConstrainedCodec.parseAsync(data);

export const getConstrainedCodec = async <ThrowOnError extends boolean = false>(options?: Options<GetConstrainedCodecData, ThrowOnError>) => await getConstrainedCodec2(options);

export type GetTupleFieldResponses = {
    200: z.output<typeof TupleField>;
};

export type GetTupleFieldResponse = GetTupleFieldResponses[keyof GetTupleFieldResponses];

export const getTupleFieldTransformer = async (data: unknown): Promise<z.output<typeof TupleField>> => await TupleField.parseAsync(data);

export const getTupleField = async <ThrowOnError extends boolean = false>(options?: Options<GetTupleFieldData, ThrowOnError>) => await getTupleField2(options);

export type GetIntersectionFieldResponses = {
    200: z.output<typeof IntersectionField>;
};

export type GetIntersectionFieldResponse = GetIntersectionFieldResponses[keyof GetIntersectionFieldResponses];

export const getIntersectionFieldTransformer = async (data: unknown): Promise<z.output<typeof IntersectionField>> => await IntersectionField.parseAsync(data);

export const getIntersectionField = async <ThrowOnError extends boolean = false>(options?: Options<GetIntersectionFieldData, ThrowOnError>) => await getIntersectionField2(options);

export type GetDiscriminatedUnionResponses = {
    200: z.output<typeof DiscriminatedUnion>;
};

export type GetDiscriminatedUnionResponse = GetDiscriminatedUnionResponses[keyof GetDiscriminatedUnionResponses];

export const getDiscriminatedUnionTransformer = async (data: unknown): Promise<z.output<typeof DiscriminatedUnion>> => await DiscriminatedUnion.parseAsync(data);

export const getDiscriminatedUnion = async <ThrowOnError extends boolean = false>(options?: Options<GetDiscriminatedUnionData, ThrowOnError>) => await getDiscriminatedUnion2(options);

export type GetDateFieldResponses = {
    200: z.output<typeof DateField>;
};

export type GetDateFieldResponse = GetDateFieldResponses[keyof GetDateFieldResponses];

export const getDateFieldTransformer = async (data: unknown): Promise<z.output<typeof DateField>> => await DateField.parseAsync(data);

export const getDateField = async <ThrowOnError extends boolean = false>(options?: Options<GetDateFieldData, ThrowOnError>) => await getDateField2(options);

export type GetSetFieldResponses = {
    200: z.output<typeof SetField>;
};

export type GetSetFieldResponse = GetSetFieldResponses[keyof GetSetFieldResponses];

export const getSetFieldTransformer = async (data: unknown): Promise<z.output<typeof SetField>> => await SetField.parseAsync(data);

export const getSetField = async <ThrowOnError extends boolean = false>(options?: Options<GetSetFieldData, ThrowOnError>) => await getSetField2(options);

export type GetMapFieldResponses = {
    200: z.output<typeof MapField>;
};

export type GetMapFieldResponse = GetMapFieldResponses[keyof GetMapFieldResponses];

export const getMapFieldTransformer = async (data: unknown): Promise<z.output<typeof MapField>> => await MapField.parseAsync(data);

export const getMapField = async <ThrowOnError extends boolean = false>(options?: Options<GetMapFieldData, ThrowOnError>) => await getMapField2(options);

export type GetDefaultFieldResponses = {
    200: z.output<typeof DefaultField>;
};

export type GetDefaultFieldResponse = GetDefaultFieldResponses[keyof GetDefaultFieldResponses];

export const getDefaultFieldTransformer = async (data: unknown): Promise<z.output<typeof DefaultField>> => await DefaultField.parseAsync(data);

export const getDefaultField = async <ThrowOnError extends boolean = false>(options?: Options<GetDefaultFieldData, ThrowOnError>) => await getDefaultField2(options);

export type GetReadonlyArrayFieldResponses = {
    200: z.output<typeof ReadonlyArrayField>;
};

export type GetReadonlyArrayFieldResponse = GetReadonlyArrayFieldResponses[keyof GetReadonlyArrayFieldResponses];

export const getReadonlyArrayFieldTransformer = async (data: unknown): Promise<z.output<typeof ReadonlyArrayField>> => await ReadonlyArrayField.parseAsync(data);

export const getReadonlyArrayField = async <ThrowOnError extends boolean = false>(options?: Options<GetReadonlyArrayFieldData, ThrowOnError>) => await getReadonlyArrayField2(options);

export type GetBrandedFieldResponses = {
    200: z.output<typeof BrandedField>;
};

export type GetBrandedFieldResponse = GetBrandedFieldResponses[keyof GetBrandedFieldResponses];

export const getBrandedFieldTransformer = async (data: unknown): Promise<z.output<typeof BrandedField>> => await BrandedField.parseAsync(data);

export const getBrandedField = async <ThrowOnError extends boolean = false>(options?: Options<GetBrandedFieldData, ThrowOnError>) => await getBrandedField2(options);

export type CreateOrFetchResourceResponses = {
    200: z.output<typeof ResourceFetched>;
    201: z.output<typeof ResourceCreated>;
};

export type CreateOrFetchResourceResponse = CreateOrFetchResourceResponses[keyof CreateOrFetchResourceResponses];

export type CreateOrFetchResourceErrors = {
    400: z.output<typeof BadRequestError>;
    404: z.output<typeof NotFoundError>;
    500: z.output<typeof ServerError>;
};

export type CreateOrFetchResourceError = CreateOrFetchResourceErrors[keyof CreateOrFetchResourceErrors];

export const createOrFetchResourceTransformer = async (data: unknown): Promise<z.output<typeof ResourceFetched> | z.output<typeof ResourceCreated>> => await z.union([ResourceFetched, ResourceCreated]).parseAsync(data);

export const createOrFetchResourceErrorTransformer = async (data: unknown): Promise<z.output<typeof BadRequestError> | z.output<typeof NotFoundError> | z.output<typeof ServerError>> => await z.union([
    BadRequestError,
    NotFoundError,
    ServerError
]).parseAsync(data);

/**
 * @internal — emitted by `@polygonlabs/zod-to-openapi-heyapi`. Do not
 * instantiate from consumer code; the wrapper constructs these in
 * response to fetch transport rejections (DNS / abort / `ECONNRESET`).
 * Narrow via the emitted `isTransportError` type-predicate guard.
 */
export class TransportError extends Error {
    readonly cause: Error;
    constructor(cause: Error) {
        super('Request failed before producing an HTTP response');
        (this as Record<symbol, unknown>)[Symbol.for("@polygonlabs/zod-to-openapi-heyapi/is-transport-error")] = true;
        this.cause = cause;
        this.name = 'TransportError';
    }
}

/**
 * @internal — emitted by `@polygonlabs/zod-to-openapi-heyapi`. Do not
 * instantiate from consumer code; the wrapper constructs these when
 * `parseAsync` rejects an HTTP error body that did not match any
 * registered error schema. `cause` carries the `ZodError` issues;
 * `body` is the original wire body for debugging schema drift.
 * Narrow via the emitted `isResponseValidationError` type-predicate guard.
 */
export class ResponseValidationError extends Error {
    readonly cause: ZodError;
    readonly body: unknown;
    constructor(cause: ZodError, body: unknown) {
        super('API response did not match the registered schema');
        (this as Record<symbol, unknown>)[Symbol.for("@polygonlabs/zod-to-openapi-heyapi/is-response-validation-error")] = true;
        this.cause = cause;
        this.name = 'ResponseValidationError';
        this.body = body;
    }
}

export const isTransportError = (value: unknown): value is TransportError => typeof value === "object" && value !== null && (value as Record<symbol, unknown>)[Symbol.for("@polygonlabs/zod-to-openapi-heyapi/is-transport-error")] === true;

export const isResponseValidationError = (value: unknown): value is ResponseValidationError => typeof value === "object" && value !== null && (value as Record<symbol, unknown>)[Symbol.for("@polygonlabs/zod-to-openapi-heyapi/is-response-validation-error")] === true;

export const isWrapperError = (value: unknown): value is TransportError | ResponseValidationError => typeof value === "object" && value !== null && ((value as Record<symbol, unknown>)[Symbol.for("@polygonlabs/zod-to-openapi-heyapi/is-transport-error")] === true || (value as Record<symbol, unknown>)[Symbol.for("@polygonlabs/zod-to-openapi-heyapi/is-response-validation-error")] === true);

export type WrapErrors<TData, TError, ThrowOnError extends boolean> = Promise<ThrowOnError extends true ? {
    data: TData extends Record<string, unknown> ? TData[keyof TData] : TData;
    request: Request;
    response: Response;
} : ({
    data: TData extends Record<string, unknown> ? TData[keyof TData] : TData;
    error: undefined;
} | {
    data: undefined;
    error: (TError extends Record<string, unknown> ? TError[keyof TError] : TError) | TransportError | ResponseValidationError;
}) & {
    request: Request;
    response: Response;
}>;

export const createOrFetchResource = async <ThrowOnError extends boolean = false>(options?: Options<CreateOrFetchResourceData, ThrowOnError>): WrapErrors<CreateOrFetchResourceResponses, CreateOrFetchResourceErrors, ThrowOnError> => {
    let result;
    try {
        result = await createOrFetchResource2(options);
    }
    catch (err) {
        if (err instanceof Error) {
            throw new TransportError(err as Error);
        }
        let typedErr;
        try {
            typedErr = await createOrFetchResourceErrorTransformer(err);
        }
        catch (validationError) {
            throw new ResponseValidationError(validationError as ZodError, err);
        }
        throw typedErr;
    }
    const errorBearing = result as {
        error?: unknown;
    };
    if (typeof errorBearing.error === "object" && errorBearing.error !== null) {
        if (errorBearing.error instanceof Error) {
            errorBearing.error = new TransportError(errorBearing.error as Error);
        }
        else {
            try {
                errorBearing.error = await createOrFetchResourceErrorTransformer(errorBearing.error);
            }
            catch (validationError) {
                errorBearing.error = new ResponseValidationError(validationError as ZodError, errorBearing.error);
            }
        }
    }
    return result as unknown as Awaited<WrapErrors<CreateOrFetchResourceResponses, CreateOrFetchResourceErrors, ThrowOnError>>;
};

export type GetErrorsOnlyErrors = {
    400: z.output<typeof BadRequestError>;
    500: z.output<typeof ServerError>;
};

export type GetErrorsOnlyError = GetErrorsOnlyErrors[keyof GetErrorsOnlyErrors];

export const getErrorsOnlyErrorTransformer = async (data: unknown): Promise<z.output<typeof BadRequestError> | z.output<typeof ServerError>> => await z.union([BadRequestError, ServerError]).parseAsync(data);

export const getErrorsOnly = async <ThrowOnError extends boolean = false>(options?: Options<GetErrorsOnlyData, ThrowOnError>): WrapErrors<unknown, GetErrorsOnlyErrors, ThrowOnError> => {
    let result;
    try {
        result = await getErrorsOnly2(options);
    }
    catch (err) {
        if (err instanceof Error) {
            throw new TransportError(err as Error);
        }
        let typedErr;
        try {
            typedErr = await getErrorsOnlyErrorTransformer(err);
        }
        catch (validationError) {
            throw new ResponseValidationError(validationError as ZodError, err);
        }
        throw typedErr;
    }
    const errorBearing = result as {
        error?: unknown;
    };
    if (typeof errorBearing.error === "object" && errorBearing.error !== null) {
        if (errorBearing.error instanceof Error) {
            errorBearing.error = new TransportError(errorBearing.error as Error);
        }
        else {
            try {
                errorBearing.error = await getErrorsOnlyErrorTransformer(errorBearing.error);
            }
            catch (validationError) {
                errorBearing.error = new ResponseValidationError(validationError as ZodError, errorBearing.error);
            }
        }
    }
    return result as unknown as Awaited<WrapErrors<unknown, GetErrorsOnlyErrors, ThrowOnError>>;
};

export type GetItemWithRegisteredParamResponses = {
    200: z.output<typeof ScalarString>;
};

export type GetItemWithRegisteredParamResponse = GetItemWithRegisteredParamResponses[keyof GetItemWithRegisteredParamResponses];

export const getItemWithRegisteredParamTransformer = async (data: unknown): Promise<z.output<typeof ScalarString>> => await ScalarString.parseAsync(data);

export const getItemWithRegisteredParam = async <ThrowOnError extends boolean = false>(options: Options<GetItemWithRegisteredParamData, ThrowOnError>) => await getItemWithRegisteredParam2(options);

export type LookupBlockResponses = {
    200: z.output<typeof ScalarString>;
};

export type LookupBlockResponse = LookupBlockResponses[keyof LookupBlockResponses];

export const lookupBlockTransformer = async (data: unknown): Promise<z.output<typeof ScalarString>> => await ScalarString.parseAsync(data);

export type LookupBlockInput = Omit<LookupBlockData, 'path'> & {
    path: z.output<typeof BlockNumberPathParams>;
};

export const lookupBlockInputTransformer = async (input: Pick<LookupBlockInput, 'path'>) => ({ ...input.path !== undefined ? { path: await z.encode(BlockNumberPathParams, input.path) } : {} });

export const lookupBlock = async <ThrowOnError extends boolean = false>(options: Options<LookupBlockInput, ThrowOnError>) => {
    const transformed = await lookupBlockInputTransformer(options);
    return await lookupBlock2({ ...options, ...transformed } as Options<LookupBlockData, ThrowOnError>);
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const lookupBlockQueryKey = (options: Options<LookupBlockInput>) => createQueryKey('lookupBlock', { ...options, ...options?.path !== undefined ? { path: z.encode(BlockNumberPathParams, options?.path) } : {} } as Options<LookupBlockData>);

export const lookupBlockOptions = (options: Options<LookupBlockInput>) => queryOptions<LookupBlockResponse, DefaultError, LookupBlockResponse, ReturnType<typeof lookupBlockQueryKey>>({ queryFn: async ({ queryKey, signal }) => {
        const { data } = await lookupBlock2({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        } as Options<LookupBlockData, true>);
        return data;
    }, queryKey: lookupBlockQueryKey(options) });

export type ListRecentEventsResponses = {
    200: z.output<typeof ScalarString>;
};

export type ListRecentEventsResponse = ListRecentEventsResponses[keyof ListRecentEventsResponses];

export const listRecentEventsTransformer = async (data: unknown): Promise<z.output<typeof ScalarString>> => await ScalarString.parseAsync(data);

export type ListRecentEventsInput = Omit<ListRecentEventsData, 'query'> & {
    query?: z.output<typeof RecentEventsQuery>;
};

export const listRecentEventsInputTransformer = async (input: Pick<ListRecentEventsInput, 'query'>) => ({ ...input.query !== undefined ? { query: await z.encode(RecentEventsQuery, input.query) } : {} });

export const listRecentEvents = async <ThrowOnError extends boolean = false>(options?: Options<ListRecentEventsInput, ThrowOnError>) => {
    const transformed = await listRecentEventsInputTransformer(options ?? {});
    return await listRecentEvents2({ ...options, ...transformed } as Options<ListRecentEventsData, ThrowOnError>);
};

export const listRecentEventsQueryKey = (options?: Options<ListRecentEventsInput>) => createQueryKey('listRecentEvents', { ...options, ...options?.query !== undefined ? { query: z.encode(RecentEventsQuery, options?.query) } : {} } as Options<ListRecentEventsData>);

export const listRecentEventsOptions = (options?: Options<ListRecentEventsInput>) => queryOptions<ListRecentEventsResponse, DefaultError, ListRecentEventsResponse, ReturnType<typeof listRecentEventsQueryKey>>({ queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRecentEvents2({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        } as Options<ListRecentEventsData, true>);
        return data;
    }, queryKey: listRecentEventsQueryKey(options) });

export type CreateOrderResponses = {
    200: z.output<typeof ScalarString>;
};

export type CreateOrderResponse = CreateOrderResponses[keyof CreateOrderResponses];

export type CreateOrderErrors = {
    400: z.output<typeof BadRequestError>;
    500: z.output<typeof ServerError>;
};

export type CreateOrderError = CreateOrderErrors[keyof CreateOrderErrors];

export const createOrderTransformer = async (data: unknown): Promise<z.output<typeof ScalarString>> => await ScalarString.parseAsync(data);

export const createOrderErrorTransformer = async (data: unknown): Promise<z.output<typeof BadRequestError> | z.output<typeof ServerError>> => await z.union([BadRequestError, ServerError]).parseAsync(data);

export type CreateOrderInput = Omit<CreateOrderData, 'body'> & {
    body: z.output<typeof CreateOrderRequest>;
};

export const createOrderInputTransformer = async (input: Pick<CreateOrderInput, 'body'>) => ({ ...input.body !== undefined ? { body: await z.encode(CreateOrderRequest, input.body) } : {} });

export const createOrder = async <ThrowOnError extends boolean = false>(options: Options<CreateOrderInput, ThrowOnError>): WrapErrors<CreateOrderResponses, CreateOrderErrors, ThrowOnError> => {
    const transformed = await createOrderInputTransformer(options);
    let result;
    try {
        result = await createOrder2({ ...options, ...transformed } as Options<CreateOrderData, ThrowOnError>);
    }
    catch (err) {
        if (err instanceof Error) {
            throw new TransportError(err as Error);
        }
        let typedErr;
        try {
            typedErr = await createOrderErrorTransformer(err);
        }
        catch (validationError) {
            throw new ResponseValidationError(validationError as ZodError, err);
        }
        throw typedErr;
    }
    const errorBearing = result as {
        error?: unknown;
    };
    if (typeof errorBearing.error === "object" && errorBearing.error !== null) {
        if (errorBearing.error instanceof Error) {
            errorBearing.error = new TransportError(errorBearing.error as Error);
        }
        else {
            try {
                errorBearing.error = await createOrderErrorTransformer(errorBearing.error);
            }
            catch (validationError) {
                errorBearing.error = new ResponseValidationError(validationError as ZodError, errorBearing.error);
            }
        }
    }
    return result as unknown as Awaited<WrapErrors<CreateOrderResponses, CreateOrderErrors, ThrowOnError>>;
};

export const createOrderQueryKey = (options: Options<CreateOrderInput>) => createQueryKey('createOrder', { ...options, ...options?.body !== undefined ? { body: z.encode(CreateOrderRequest, options?.body) } : {} } as Options<CreateOrderData>);

export const createOrderOptions = (options: Options<CreateOrderInput>) => queryOptions<CreateOrderResponse, CreateOrderError, CreateOrderResponse, ReturnType<typeof createOrderQueryKey>>({ queryFn: async ({ queryKey, signal }) => {
        const { data } = await createOrder2({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        } as Options<CreateOrderData, true>);
        return data;
    }, queryKey: createOrderQueryKey(options) });

export type UpdateOrderResponses = {
    200: z.output<typeof ScalarString>;
};

export type UpdateOrderResponse = UpdateOrderResponses[keyof UpdateOrderResponses];

export const updateOrderTransformer = async (data: unknown): Promise<z.output<typeof ScalarString>> => await ScalarString.parseAsync(data);

export type UpdateOrderInput = Omit<UpdateOrderData, 'path' | 'body'> & {
    path: z.output<typeof OrderIdPathParams>;
    body: z.output<typeof UpdateOrderRequest>;
};

export const updateOrderInputTransformer = async (input: Pick<UpdateOrderInput, 'path' | 'body'>) => ({ ...input.path !== undefined ? { path: await z.encode(OrderIdPathParams, input.path) } : {}, ...input.body !== undefined ? { body: await z.encode(UpdateOrderRequest, input.body) } : {} });

export const updateOrder = async <ThrowOnError extends boolean = false>(options: Options<UpdateOrderInput, ThrowOnError>) => {
    const transformed = await updateOrderInputTransformer(options);
    return await updateOrder2({ ...options, ...transformed } as Options<UpdateOrderData, ThrowOnError>);
};

export const updateOrderQueryKey = (options: Options<UpdateOrderInput>) => createQueryKey('updateOrder', {
    ...options,
    ...options?.path !== undefined ? { path: z.encode(OrderIdPathParams, options?.path) } : {},
    ...options?.body !== undefined ? { body: z.encode(UpdateOrderRequest, options?.body) } : {}
} as Options<UpdateOrderData>);

export const updateOrderOptions = (options: Options<UpdateOrderInput>) => queryOptions<UpdateOrderResponse, DefaultError, UpdateOrderResponse, ReturnType<typeof updateOrderQueryKey>>({ queryFn: async ({ queryKey, signal }) => {
        const { data } = await updateOrder2({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        } as Options<UpdateOrderData, true>);
        return data;
    }, queryKey: updateOrderQueryKey(options) });

export type SubmitForReviewResponses = {
    200: z.output<typeof ScalarString>;
};

export type SubmitForReviewResponse = SubmitForReviewResponses[keyof SubmitForReviewResponses];

export const submitForReviewTransformer = async (data: unknown): Promise<z.output<typeof ScalarString>> => await ScalarString.parseAsync(data);

export type SubmitForReviewInput = Omit<SubmitForReviewData, 'body'> & {
    body?: z.output<typeof SubmitForReviewRequest>;
};

export const submitForReviewInputTransformer = async (input: Pick<SubmitForReviewInput, 'body'>) => ({ ...input.body !== undefined ? { body: await z.encode(SubmitForReviewRequest, input.body) } : {} });

export const submitForReview = async <ThrowOnError extends boolean = false>(options?: Options<SubmitForReviewInput, ThrowOnError>) => {
    const transformed = await submitForReviewInputTransformer(options ?? {});
    return await submitForReview2({ ...options, ...transformed } as Options<SubmitForReviewData, ThrowOnError>);
};

export const submitForReviewQueryKey = (options?: Options<SubmitForReviewInput>) => createQueryKey('submitForReview', { ...options, ...options?.body !== undefined ? { body: z.encode(SubmitForReviewRequest, options?.body) } : {} } as Options<SubmitForReviewData>);

export const submitForReviewOptions = (options?: Options<SubmitForReviewInput>) => queryOptions<SubmitForReviewResponse, DefaultError, SubmitForReviewResponse, ReturnType<typeof submitForReviewQueryKey>>({ queryFn: async ({ queryKey, signal }) => {
        const { data } = await submitForReview2({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        } as Options<SubmitForReviewData, true>);
        return data;
    }, queryKey: submitForReviewQueryKey(options) });
