// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ScalarString = {
    value: string;
};

export type ScalarNumber = {
    value: number;
};

export type ScalarBoolean = {
    value: boolean;
};

export type ScalarBigInt = {
    value: string;
};

export type OptionalField = {
    required: string;
    optional?: string;
};

export type NullableField = {
    required: string;
    nullable: string | null;
};

export type OptionalNullableField = {
    required: string;
    optionalNullable?: string | null;
};

export type EnumField = {
    status: 'pending' | 'active' | 'archived';
};

export type LiteralField = {
    type: 'payment';
};

export type UnionOfLiterals = {
    kind: 'a' | 'b' | 'c';
};

export type ArrayOfScalars = {
    tags: Array<string>;
};

export type ArrayOfCodecs = {
    amounts: Array<string>;
};

export type RecordField = {
    metadata: {
        [key: string]: string;
    };
};

export type Nested = {
    outer: {
        inner: {
            deep: string;
        };
    };
};

export type UnionField = {
    payload: string | number;
};

export type CodecObject = {
    id: string;
    amount: string;
    currency: string;
    fee: string;
    createdAt: string;
};

export type Composed = {
    id: string;
    status: 'pending' | 'completed';
    amount: string;
    metadata?: {
        [key: string]: string;
    };
    tags?: Array<string>;
    parent?: {
        id: string;
        childAmount: string;
    } | null;
};

export type PaginatedComposed = {
    hasMore?: boolean;
    data?: Array<{
        id: string;
        status: 'pending' | 'completed';
        amount: string;
        metadata?: {
            [key: string]: string;
        };
        tags?: Array<string>;
        parent?: {
            id: string;
            childAmount: string;
        } | null;
    }>;
};

export type StringWithMinMax = {
    short: string;
    long: string;
};

export type NumberWithRange = {
    count: number;
    ratio: number;
};

export type ArrayWithLength = {
    items: Array<string>;
};

export type StringWithFormat = {
    email: string;
    url: string;
    uuid: string;
};

export type RefinedField = {
    notEmpty: string;
};

export type ConstrainedCodec = {
    amount: string;
};

export type TupleField = {
    pair: [
        string | number,
        string | number
    ];
    pairWithCodec: [
        string | string,
        string | string
    ];
};

export type IntersectionField = {
    a: string;
} & {
    b: number;
};

export type DiscriminatedUnion = {
    kind: 'text';
    text: string;
} | {
    kind: 'number';
    value: number;
} | {
    kind: 'amount';
    amount: string;
};

export type DateField = {
    occurredAt: string;
};

export type SetField = {
    ids: Array<string>;
};

export type MapField = {
    byId: {
        [key: string]: number;
    };
};

export type DefaultField = {
    status?: string;
};

export type ReadonlyArrayField = {
    tags: Array<string>;
};

export type BrandedField = {
    userId: string;
};

export type BadRequestError = {
    code: 'bad_request';
    message: string;
    fieldErrors?: {
        [key: string]: string;
    };
};

export type NotFoundError = {
    code: 'not_found';
    message: string;
    resourceId: string;
};

export type ServerError = {
    code: 'internal_error';
    message: string;
    traceId: string;
};

export type ResourceFetched = {
    id: string;
    data: string;
};

export type ResourceCreated = {
    id: string;
    createdAt: string;
};

export type GetScalarStringData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getScalarString';
};

export type GetScalarStringResponses = {
    /**
     * ok
     */
    200: ScalarString;
};

export type GetScalarStringResponse = GetScalarStringResponses[keyof GetScalarStringResponses];

export type GetScalarNumberData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getScalarNumber';
};

export type GetScalarNumberResponses = {
    /**
     * ok
     */
    200: ScalarNumber;
};

export type GetScalarNumberResponse = GetScalarNumberResponses[keyof GetScalarNumberResponses];

export type GetScalarBooleanData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getScalarBoolean';
};

export type GetScalarBooleanResponses = {
    /**
     * ok
     */
    200: ScalarBoolean;
};

export type GetScalarBooleanResponse = GetScalarBooleanResponses[keyof GetScalarBooleanResponses];

export type GetScalarBigIntData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getScalarBigInt';
};

export type GetScalarBigIntResponses = {
    /**
     * ok
     */
    200: ScalarBigInt;
};

export type GetScalarBigIntResponse = GetScalarBigIntResponses[keyof GetScalarBigIntResponses];

export type GetOptionalFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getOptionalField';
};

export type GetOptionalFieldResponses = {
    /**
     * ok
     */
    200: OptionalField;
};

export type GetOptionalFieldResponse = GetOptionalFieldResponses[keyof GetOptionalFieldResponses];

export type GetNullableFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getNullableField';
};

export type GetNullableFieldResponses = {
    /**
     * ok
     */
    200: NullableField;
};

export type GetNullableFieldResponse = GetNullableFieldResponses[keyof GetNullableFieldResponses];

export type GetOptionalNullableFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getOptionalNullableField';
};

export type GetOptionalNullableFieldResponses = {
    /**
     * ok
     */
    200: OptionalNullableField;
};

export type GetOptionalNullableFieldResponse = GetOptionalNullableFieldResponses[keyof GetOptionalNullableFieldResponses];

export type GetEnumFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getEnumField';
};

export type GetEnumFieldResponses = {
    /**
     * ok
     */
    200: EnumField;
};

export type GetEnumFieldResponse = GetEnumFieldResponses[keyof GetEnumFieldResponses];

export type GetLiteralFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getLiteralField';
};

export type GetLiteralFieldResponses = {
    /**
     * ok
     */
    200: LiteralField;
};

export type GetLiteralFieldResponse = GetLiteralFieldResponses[keyof GetLiteralFieldResponses];

export type GetUnionOfLiteralsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getUnionOfLiterals';
};

export type GetUnionOfLiteralsResponses = {
    /**
     * ok
     */
    200: UnionOfLiterals;
};

export type GetUnionOfLiteralsResponse = GetUnionOfLiteralsResponses[keyof GetUnionOfLiteralsResponses];

export type GetArrayOfScalarsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getArrayOfScalars';
};

export type GetArrayOfScalarsResponses = {
    /**
     * ok
     */
    200: ArrayOfScalars;
};

export type GetArrayOfScalarsResponse = GetArrayOfScalarsResponses[keyof GetArrayOfScalarsResponses];

export type GetArrayOfCodecsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getArrayOfCodecs';
};

export type GetArrayOfCodecsResponses = {
    /**
     * ok
     */
    200: ArrayOfCodecs;
};

export type GetArrayOfCodecsResponse = GetArrayOfCodecsResponses[keyof GetArrayOfCodecsResponses];

export type GetRecordFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getRecordField';
};

export type GetRecordFieldResponses = {
    /**
     * ok
     */
    200: RecordField;
};

export type GetRecordFieldResponse = GetRecordFieldResponses[keyof GetRecordFieldResponses];

export type GetNestedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getNested';
};

export type GetNestedResponses = {
    /**
     * ok
     */
    200: Nested;
};

export type GetNestedResponse = GetNestedResponses[keyof GetNestedResponses];

export type GetUnionFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getUnionField';
};

export type GetUnionFieldResponses = {
    /**
     * ok
     */
    200: UnionField;
};

export type GetUnionFieldResponse = GetUnionFieldResponses[keyof GetUnionFieldResponses];

export type GetCodecObjectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getCodecObject';
};

export type GetCodecObjectResponses = {
    /**
     * ok
     */
    200: CodecObject;
};

export type GetCodecObjectResponse = GetCodecObjectResponses[keyof GetCodecObjectResponses];

export type GetComposedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getComposed';
};

export type GetComposedResponses = {
    /**
     * ok
     */
    200: Composed;
};

export type GetComposedResponse = GetComposedResponses[keyof GetComposedResponses];

export type GetPaginatedComposedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getPaginatedComposed';
};

export type GetPaginatedComposedResponses = {
    /**
     * ok
     */
    200: PaginatedComposed;
};

export type GetPaginatedComposedResponse = GetPaginatedComposedResponses[keyof GetPaginatedComposedResponses];

export type GetStringWithMinMaxData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getStringWithMinMax';
};

export type GetStringWithMinMaxResponses = {
    /**
     * ok
     */
    200: StringWithMinMax;
};

export type GetStringWithMinMaxResponse = GetStringWithMinMaxResponses[keyof GetStringWithMinMaxResponses];

export type GetNumberWithRangeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getNumberWithRange';
};

export type GetNumberWithRangeResponses = {
    /**
     * ok
     */
    200: NumberWithRange;
};

export type GetNumberWithRangeResponse = GetNumberWithRangeResponses[keyof GetNumberWithRangeResponses];

export type GetArrayWithLengthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getArrayWithLength';
};

export type GetArrayWithLengthResponses = {
    /**
     * ok
     */
    200: ArrayWithLength;
};

export type GetArrayWithLengthResponse = GetArrayWithLengthResponses[keyof GetArrayWithLengthResponses];

export type GetStringWithFormatData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getStringWithFormat';
};

export type GetStringWithFormatResponses = {
    /**
     * ok
     */
    200: StringWithFormat;
};

export type GetStringWithFormatResponse = GetStringWithFormatResponses[keyof GetStringWithFormatResponses];

export type GetRefinedFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getRefinedField';
};

export type GetRefinedFieldResponses = {
    /**
     * ok
     */
    200: RefinedField;
};

export type GetRefinedFieldResponse = GetRefinedFieldResponses[keyof GetRefinedFieldResponses];

export type GetConstrainedCodecData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getConstrainedCodec';
};

export type GetConstrainedCodecResponses = {
    /**
     * ok
     */
    200: ConstrainedCodec;
};

export type GetConstrainedCodecResponse = GetConstrainedCodecResponses[keyof GetConstrainedCodecResponses];

export type GetTupleFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getTupleField';
};

export type GetTupleFieldResponses = {
    /**
     * ok
     */
    200: TupleField;
};

export type GetTupleFieldResponse = GetTupleFieldResponses[keyof GetTupleFieldResponses];

export type GetIntersectionFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getIntersectionField';
};

export type GetIntersectionFieldResponses = {
    /**
     * ok
     */
    200: IntersectionField;
};

export type GetIntersectionFieldResponse = GetIntersectionFieldResponses[keyof GetIntersectionFieldResponses];

export type GetDiscriminatedUnionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getDiscriminatedUnion';
};

export type GetDiscriminatedUnionResponses = {
    /**
     * ok
     */
    200: DiscriminatedUnion;
};

export type GetDiscriminatedUnionResponse = GetDiscriminatedUnionResponses[keyof GetDiscriminatedUnionResponses];

export type GetDateFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getDateField';
};

export type GetDateFieldResponses = {
    /**
     * ok
     */
    200: DateField;
};

export type GetDateFieldResponse = GetDateFieldResponses[keyof GetDateFieldResponses];

export type GetSetFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getSetField';
};

export type GetSetFieldResponses = {
    /**
     * ok
     */
    200: SetField;
};

export type GetSetFieldResponse = GetSetFieldResponses[keyof GetSetFieldResponses];

export type GetMapFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getMapField';
};

export type GetMapFieldResponses = {
    /**
     * ok
     */
    200: MapField;
};

export type GetMapFieldResponse = GetMapFieldResponses[keyof GetMapFieldResponses];

export type GetDefaultFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getDefaultField';
};

export type GetDefaultFieldResponses = {
    /**
     * ok
     */
    200: DefaultField;
};

export type GetDefaultFieldResponse = GetDefaultFieldResponses[keyof GetDefaultFieldResponses];

export type GetReadonlyArrayFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getReadonlyArrayField';
};

export type GetReadonlyArrayFieldResponses = {
    /**
     * ok
     */
    200: ReadonlyArrayField;
};

export type GetReadonlyArrayFieldResponse = GetReadonlyArrayFieldResponses[keyof GetReadonlyArrayFieldResponses];

export type GetBrandedFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/getBrandedField';
};

export type GetBrandedFieldResponses = {
    /**
     * ok
     */
    200: BrandedField;
};

export type GetBrandedFieldResponse = GetBrandedFieldResponses[keyof GetBrandedFieldResponses];

export type CreateOrFetchResourceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/createOrFetch';
};

export type CreateOrFetchResourceErrors = {
    /**
     * bad request
     */
    400: BadRequestError;
    /**
     * not found
     */
    404: NotFoundError;
    /**
     * server error
     */
    500: ServerError;
};

export type CreateOrFetchResourceError = CreateOrFetchResourceErrors[keyof CreateOrFetchResourceErrors];

export type CreateOrFetchResourceResponses = {
    /**
     * fetched
     */
    200: ResourceFetched;
    /**
     * created
     */
    201: ResourceCreated;
};

export type CreateOrFetchResourceResponse = CreateOrFetchResourceResponses[keyof CreateOrFetchResourceResponses];

export type GetErrorsOnlyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fixtures/errorsOnly';
};

export type GetErrorsOnlyErrors = {
    /**
     * bad request
     */
    400: BadRequestError;
    /**
     * server error
     */
    500: ServerError;
};

export type GetErrorsOnlyError = GetErrorsOnlyErrors[keyof GetErrorsOnlyErrors];
